# Generated by Django 4.2 on 2023-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_name', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=3000)),
                ('Date', models.DateField()),
            ],
        ),
    ]
