# Generated by Django 4.2 on 2023-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_delete_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='sr_no',
            new_name='sno',
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
